### ISSUE TITLE
CRF with custom features

### ISSUE THREAD

**Issue by bratao** [nanguoshun/StatNLP-Framework#1]
First of all, congratulations for this project. I´m impressed by the speed and quality of the code you´re creating.

I have a question, and I wonder if you @nanguoshun , can guide me

CRFsuite and CRF++ allow us to use "custom features" for training and tagging. This is very important for my case, as we have another features such formatting and position. 

Could I use StatNLP for this use case?

Thank you!

**Comment by nanguoshun** [comment]
Hi bratao, thanks for your interest to our statNLP framework.

YES, You can use customized features by implementing ExtractHelper, which is a virtual function of the class FeatureManager.  You can refer to the implementation of FeatureArray* LinearCRFFeatureManager::ExtractHelper(Network *ptr_network, int parent_k, int *ptr_children) under src/example/LinearCRF.

For more details, please refer to our released version written in Java at https://gitlab.com/sutd_nlp/statnlp-core, as well as a tutorial given by Prof Lu Wei at EMNLP 2017  http://www.statnlp.org/tutorials. Thanks a lot!

**Comment by bratao** [comment]
Awesome, 

I will try. Thank you for the attention!
